In [2]:
import numpy as np

In [37]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
mean_a=a.mean(axis=0)
mean_a


array([2. , 8.4])

In [55]:
a_centered=np.array(a-mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [73]:
skalyar=7
a_centered_sp=a_centered*skalyar/a_centered.shape[0]
a_centered_sp

array([[-1.4 , -3.36],
       [ 0.  , -0.56],
       [ 1.4 ,  3.64],
       [ 1.4 ,  2.24],
       [-1.4 , -1.96]])

In [77]:
import pandas as pd

In [97]:
authors =pd.DataFrame( 
    {"author_id":[1,2,3],
    "author_name":['Тургенев', 'Чехов','Островский']})
authors


author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [98]:
book = pd.DataFrame({
    "author_id" : [1,1,1,2,2,3,3],
    "book_title" : ['Отцы и дети','Рудин','Дворянское гнездо','Толстый и тонкий','Дама с собачкой','Гроза','Таланты и поклонники'],
    "price" : [450,300,350,500,450,370,290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [107]:
authors_price=pd.merge(authors,book, on = "author_id", how="inner")
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [155]:
authors_price.sort_values(by="price", ascending = False)
authors_price[2:7]

author_id author_name         book_title  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

In [170]:
authors_stat1=authors_price.agg({'price':min})
authors_stat

price    290
dtype: int64

In [172]:
authors_stat2=authors_price.agg({'price':max})
authors_stat2

price    500
dtype: int64